language: android
#- echo yes | android update sdk -a -t tools,platform-tools,extra-android-support,extra-android-m2repository,android-19,build-tools-19.1.0,extra-google-google_play_services,extra-google-m2repository --force --no-ui
android:
   components:
   - tools
   - platform-tools
   - android-19
   - build-tools-20.0.0
   - extra
jdk: oraclejdk7

before_install:
  # required libs for android build tools
  - sudo apt-get update
  - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
  # Don't really need this (NDK stuff) for Mibarim, but figured I'd leave it here for anyone who forks it. :)
  # newest Android NDK
  #- if [ `uname -m` = x86_64]; then wget http://dl.google.com/android/ndk/android-ndk-r9c-linux-x86_64.tar.bz2 -O ndk.tgz; else wget http://dl.google.com/android/ndk/android-ndk-r9c-linux-x86.tar.bz2 -O ndk.tgz; fi
  #- tar -xf ndk.tgz
  #- export ANDROID_NDK_HOME=`pwd`/android-ndk-r9c
  #- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_NDK_HOME}